### ISSUE TITLE
Close button shows on mouse hover

### ISSUE THREAD

**Issue by didriksg** [raflop/ToastNotifications#39]
The close button starts to show on mouse hover, even though I have set the `ShowCloseButton = false`
This only occurs in the newest 2.2.0 version, and not in the earlier 2.1.3 version

**Comment by b-mi** [comment]
This is because of new Notification property MessageOptions.FreezeOnMouseEnter, which has default value true. It allow to user cancel automatic hide of notification - by mouse entering - if user don't want the message automatic hide and user want read message. This can be solve by setting MessageNotification.FreezeOnMouseEnter to false, or change initialization value of FreezeOnMouseEnter to false. Im not sure what is better. I'm not sure, if automatic hide of notification without possibility stop to hide notification should be default setting.

**Comment by didriksg** [comment]
Ah. I see your point. For my specific use, I do not want the user to be able to cancel out the notification without taking the appropriate actions, but I see that it might be more useful to have the user able to cancel out the notification.

Thank you for your quick response :)
