### ISSUE TITLE
Stacking Notifications

### ISSUE THREAD

**Issue by didriksg** [raflop/ToastNotifications#40]
Is it possible to control the Z index of several Notifiers? I have experienced that if I use more than one notifier in my application (with different settings like liftime etc.) they tend to stack on top of each other. Is there any way I can control this?

**Comment by raflop** [comment]
Every Notifier produces its own window in which notifications are displayed.
If you could create a example how to order child windows in WPF application I could add this mechanism to notifier in some way :)

**Comment by didriksg** [comment]
I do not think WPF windows support Z-indexing, but you could maybe do something like `Window.Focus()`, `Window.Activate()` or `Window.Show()` for a simple fix. Maybe properties like the `Window.TopMost` would work in a way as well? I think that being creative with the focus, activate and show methods, that it would be possible to make an easy (and maybe a bit too simple) fix.

If you do not want to add this to the official github, where should I eventually start to make my own fix? :)

**Comment by raflop** [comment]
https://github.com/raflop/ToastNotifications/blob/master-v2/Docs/Configuration.md


There is an option to set Notifier to show topmost.


I'm not sure if forcing activate or focus will be good in every application, because this may introduce errors or bad behaviour and irritates users.


Example: User is typing / filling some form, in backgroud some event happens and notification is shown, because will be moved to notification window, user would be forced to stop typing and switch focus to main window.


You can try to add this behaviour on your fork, and create pull request if you get something working, I could test it and include in library if this will be working in some predictable and safe way.


DisplaySupervisor and Notifications window are places where you should start looking.

[https://avatars2.githubusercontent.com/u/10331492?v=3&s=400]<https://github.com/raflop/ToastNotifications/blob/master-v2/Docs/Configuration.md>

raflop/ToastNotifications<https://github.com/raflop/ToastNotifications/blob/master-v2/Docs/Configuration.md>
github.com
ToastNotifications - Toast notifications for WPF allows you to create and display rich notifications in WPF applications. It's highly configurable with set of built-in options like posi...





________________________________
Od: Didrik Galteland <notifications@github.com>
Wysłane: 26 czerwca 2017 17:16
Do: raflop/ToastNotifications
DW: Rafał; Comment
Temat: Re: [raflop/ToastNotifications] Stacking Notifications (#40)


I do not think WPF windows support Z-indexing, but you could maybe do something like Window.Focus(), Window.Activate() or Window.Show() for a simple fix. Maybe properties like the Window.TopMost would work in a way as well? I think that being creative with the focus, activate and show methods, that it would be possible to make an easy (and maybe a bit too simple) fix.

If you do not want to add this to the official github, where should I eventually start to make my own fix? :)

**Comment by didriksg** [comment]
I will look into it. Thanks for your help! :)

**Comment by b-mi** [comment]
In application with one notifier in Window is all ok, if TopMost option is false - window deactivation / activation hide and show notifications, and move them if Window is moved.
This do not work, if (more) Notifiers are attached to Controls in (WPF MDI) application. Then hiding / showing / moving of notifications do not work like it work on Window. Is this similar to your scenario?

**Comment by didriksg** [comment]
Setting the topmost property worked for my use, so no worries :)

**Comment by raflop** [comment]
Great to hear that ??

Od: Didrik Galteland<mailto:notifications@github.com>
Wysłano: poniedziałek, 26 czerwca 2017 21:45
Do: raflop/ToastNotifications<mailto:ToastNotifications@noreply.github.com>
DW: Rafał<mailto:rafal.lopatka@outlook.com>; Comment<mailto:comment@noreply.github.com>
Temat: Re: [raflop/ToastNotifications] Stacking Notifications (#40)


Setting the topmost property worked for my use, so no worries :)
