### ISSUE TITLE
 FreezeOnMouseEnter option turn off closing notification

### ISSUE THREAD

**Issue by dualbios** [raflop/ToastNotifications#48]
Proposal.
Actual: The FreezeOnMouseEnter option turn off closing after mouse leave the notification control.
Notification never closed by timer.
Expected: the notification control will close after mouse leave the control and the time to closing of notification has been finished.
the notification control stay opened when mouse is over.

**Comment by b-mi** [comment]
I like this idea. I added new message property UnfreezeOnMouseLeave (in my Fork). If UnfreezeOnMouseLeave is true, mouse enter do not show close button and notification stay visible and it hide after mouse leave (according to timer setting). I created UnfreezeOnMouseLeave  because I want preserve previous functionality.
I created pull request too.

**Comment by raflop** [comment]
Your pull request is now merged, it will be released in version 2.2.2
