### ISSUE TITLE
Crash using into usercontrol

### ISSUE THREAD

**Issue by stefanofalasca** [raflop/ToastNotifications#52]
I tried to make simple use into user control like follow code, it crash

Notifier notifier = new Notifier(cfg =>
      {
        cfg.PositionProvider = new PrimaryScreenPositionProvider(
            corner: Corner.TopRight,
            offsetX: 10,
            offsetY: 10);

        cfg.LifetimeSupervisor = new TimeAndCountBasedLifetimeSupervisor(
            notificationLifetime: TimeSpan.FromSeconds(3),
            maximumNotificationCount: MaximumNotificationCount.FromCount(5));

        cfg.Dispatcher = Dispatcher.CurrentDispatcher;
      });
      notifier.ShowInformation("CIAO");

**Comment by b-mi** [comment]
I used your code with one modification  (see line with cfg.Dispatcher) and it work:

```
Notifier notifier = new Notifier(cfg =>
            {
                cfg.PositionProvider = new PrimaryScreenPositionProvider(
                corner: Corner.TopRight,
                offsetX: 10,
                offsetY: 10);

                cfg.LifetimeSupervisor = new TimeAndCountBasedLifetimeSupervisor(
                    notificationLifetime: TimeSpan.FromSeconds(3),
                    maximumNotificationCount: MaximumNotificationCount.FromCount(5));

                cfg.Dispatcher = Application.Current.Dispatcher;
            });
            notifier.ShowInformation("CIAO");

```

**Comment by raflop** [comment]
Hi,

Is that possible that you tried to create instance of notifier not in UI Thread ? 
In that case first example use dispatcher from that thread and app crash because WPF doesn't allow that

Your second example is the way how it should be done. Just like in docs.
https://github.com/raflop/ToastNotifications/blob/master-v2/Docs/Configuration.md#dispatcher

You can even omit assigning dispatcher because Application.Current.Dispatcher is a default value for it in the library

Best regards
