### ISSUE TITLE
Adding links into toast

### ISSUE THREAD

**Issue by julioz2** [raflop/ToastNotifications#55]
Hi.
Thanks for this wonderful plugin!

Is it possible to add links or any XAML code inside the toast?

Thanks.
Giulio

**Comment by b-mi** [comment]
Hi, I need something like this too, and I have in progress ability to add action buttons into message. Every message can have his own action buttons with custom click events. It looke like this: 
https://i.imgur.com/3dTS030.png

**Comment by raflop** [comment]
Hi,

By design you can achieve this creating custom notifications, where you can put anything you want, it's quite simple - it's a user control with your own xaml

Here are some details:
https://github.com/raflop/ToastNotifications/blob/master-v2/Docs/CustomNotificatios.md

@b-mi if you have some reusable solution already and if you would like to share it, we could create separate nuget fot it, just like ToastNotifications.Messages.

I don't wan't to put everything to single lib, because not everyone use all features, and its easier to maintain when it's small.

Best regards

**Comment by b-mi** [comment]
My solution for action buttons is based on MessageOptions extension. So, if MessageOptions property is not set, action button are not used. Then, I probably add functionality for MaxHeight of Message, and allow scroll content of message if it is large..... If someone will need it, I can share.

Best regards
