### ISSUE TITLE
Unable to build version 2.3.4.0  in release mode 

### ISSUE THREAD

**Issue by udaykolluru** [raflop/ToastNotifications#80]
![toastnotification](https://user-images.githubusercontent.com/6603483/48660320-d468fb80-ea85-11e8-8f31-63ced8d87f6c.PNG)

I am trying to build the version 2.3.4.0 in VS 2017  which is giving me build errors which are attached in screen shot, any help is appreciated.

**Comment by rafallopatka** [comment]
Hi,

This is because signing key which I use to sign libraries is private. Disable assembly signing in project options or edit project file.

Best regards,
Rafał Łopatka
W dniu 17 lis 2018, o 11:59, użytkownik udaykolluru <notifications@github.com<mailto:notifications@github.com>> napisał:

[toastnotification]<https://user-images.githubusercontent.com/6603483/48660320-d468fb80-ea85-11e8-8f31-63ced8d87f6c.PNG>

I am trying to build the version 2.3.4.0 in VS 2013 which is giving me build errors which are attached in screen shot, any help is appreciated.

**Comment by udaykolluru** [comment]
Thanks , 
Working fine ......
